---
driver:
  name: docker
  provision_command:
  - yum update -y

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_chef_for_busser: false
  require_ruby_for_busser: false

platforms:
  - name: centos-6.6

suites:
   - name: apache_server
     provisioner:
        name: ansible_playbook
        playbook: test/integration/default.yml
