---
# This task installs and enables apache on webservers
- name: ensure apache is installed
  yum: pkg=httpd update_cache=yes state=latest
- name: ensure apache is running
  service: name=httpd state=running enabled=yes
  notify: restart apache
